# Generated by Django 4.1.2 on 2022-12-01 13:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, null=True)),
                ('solution', models.CharField(max_length=255, null=True)),
                ('test_input', models.CharField(max_length=255, null=True)),
                ('correct_output', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default=None, max_length=255, null=True)),
                ('output', models.CharField(default=None, max_length=255, null=True)),
                ('exercise', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_done', to='api.exercise')),
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='student_submit', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=None, null=True)),
                ('room_url', models.URLField(default=None, null=True)),
                ('students', models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, related_name='students_on_classroom', to='api.member')),
                ('subjects', models.ForeignKey(default=[], on_delete=django.db.models.deletion.PROTECT, related_name='subjects_of_classroom', to='api.exercise')),
                ('teacher', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_admin', to='api.member')),
            ],
        ),
    ]
