# Generated by Django 4.1.2 on 2022-12-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_classroom_id_alter_classroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='exercise_done', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='student_submit', to='api.student'),
        ),
    ]
