# Generated by Django 4.1.2 on 2023-01-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_solution_exercise_alter_solution_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='output',
        ),
    ]
