# Generated by Django 4.1.2 on 2022-12-05 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_teacher_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
