# Generated by Django 4.1.2 on 2022-11-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_member_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
