# Generated by Django 4.1.2 on 2023-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentprofile_teacherprofile_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
