# Generated by Django 4.1.2 on 2023-01-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_classroom_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='output',
        ),
    ]
