name: TEST DJANGO
on:
  [pull_request, push]
jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose build
      - name: Start containers
        run: docker-compose up -d
      - name: Launch tests
        run: docker-compose exec -T back python manage.py test