name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@back_dev
      - name: Start containers
        run: ./back_dev/docker-compose build
      - run: pip install flake8
      - run: flake8 . # run flake8 test
