name: TEST DJANGOOOO
on:
  [pull_request, push]
jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose build
      - name: Start containers
        run: docker-compose up -d
      - name: Back-end docker
        run: docker-compose exec back /bin/bash
      - name: Launch test
        run: python manage.py test